{
    "cve": {
        "id": "CVE-2022-29885",
        "year": 2022,
        "vuln_type": "",
        "publish_date": "2022-05-12",
        "update_date": "2022-07-25"
    },
    "cvss": {
        "score": "5.0",
        "criticity": "Medium",
        "gained_access_level": "None",
        "access": "Remote",
        "complexity": "Low",
        "confidentiality": "None",
        "integrity": "None",
        "availablility": "None"
    },
    "affected_versions": [
        {
            "tag": "10.1.0-Milestone1",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone1",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone2",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone2",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone3",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone3",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone4",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone4",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone5",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone5",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone6",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone6",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone7",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone7",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone8",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone8",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone9",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone9",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone10",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone10",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone11",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone11",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone12",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone12",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone13",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone13",
            "edition": "*"
        },
        {
            "tag": "10.1.0-Milestone14",
            "version": "10.1.0",
            "language": "*",
            "update": "Milestone14",
            "edition": "*"
        }
    ],
    "references": [
        "https://lists.apache.org/thread/2b4qmhbcyqvc7dyfpjyx54c03x65vhcv",
        "https://nvd.nist.gov/vuln/detail/CVE-2022-29885",
        "https://security.netapp.com/advisory/ntap-20220629-0002/",
        "https://www.oracle.com/security-alerts/cpujul2022.html"
    ],
    "description": "The documentation of Apache Tomcat 10.1.0-M1 to 10.1.0-M14, 10.0.0-M1 to 10.0.20, 9.0.13 to 9.0.62 and 8.5.38 to 8.5.78 for the EncryptInterceptor incorrectly stated it enabled Tomcat clustering to run over an untrusted network. This was not correct. While the EncryptInterceptor does provide confidentiality and integrity protection, it does not protect against all risks associated with running over any untrusted network, particularly DoS risks."
}