purerouter/__init__.py,sha256=p5B48TmnuKnu_bIe9srRJjX1EfhIGbjDtbiiVVpXtms,177
purerouter/client.py,sha256=Y-ZCMqO-4rVB33uepOgTPcjvKIU5rLTzhGg0Aipg0Cc,4549
purerouter/errors.py,sha256=FxRRvzCaKjMqCzYaWAxDafsSbdYgnIJK2-a8VAijx6E,310
purerouter/types.py,sha256=KgmTzt2aCS2mrbiyO3CvZxH7N2jhISe0X6WufE-ookQ,1346
purerouter/resources/deployments.py,sha256=aubhTC6wb_19FzDjoplkUTrOrWiOFX3C-bPodY_ZuNA,3540
purerouter/resources/router.py,sha256=7EeHYJnNOvbtR-h4wwpjvhq5lgtp8fkAcH93tO0n52g,3086
purerouter-0.1.1.dist-info/METADATA,sha256=OwvYZMo-rHyP1fAL9-OElwcHmzmYl6TWHK0MvefE7CI,319
purerouter-0.1.1.dist-info/WHEEL,sha256=_zCd3N1l69ArxyTb8rzEoP9TpbYXkqRFSNOD5OuxnTs,91
purerouter-0.1.1.dist-info/top_level.txt,sha256=G0zm6vmPkNMETwTPSgJABj8mgb6RGVVRLp5bVwPKscU,11
purerouter-0.1.1.dist-info/RECORD,,
